# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=5)),
                ('contactNo', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
